### ISSUE TITLE
Check and update manifold system for OEX

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#105]
Manifold system should be in grey tank in Hangar 32, and will need to be inventoried before van doors close. Additional hose nozzles may need to be purchased this year.

**Comment by MargaretSiple-NOAA** [comment]
- Susanne and I went through the manifold system, removed extraneous parts, marked which ones we need, and added lubricant to all the quick-connect hose things that needed help. 
- We found parts that need to be ordered and Susanne sent them to Nate (list screenshot below). 
- We started a doc [here ](https://docs.google.com/document/d/1U9Rk5C0BkuMHtFSJhLdtf0utV79F-79--h6au8S5V2U/edit) with more detailed instructions for how to prepare the hose setup for sea. 
- Per Susanne, the Leg 1 DL on the OEX each year should be involved in this task so they know what they're working with, so tagging @pearlrojas so she knows (Pearl, you don't actually have to do anything this is just FYI).

**We still need to clean up the ends of the hoses and some of the hose clamps, and add the extra parts that Nate orders to the kit.**

![image](https://github.com/afsc-gap-products/GOA-AI-Survey-Planning/assets/73858992/527d19dc-5f3c-4701-9f87-2c8dddc67d84)

**Comment by MargaretSiple-NOAA** [comment]
Sus and I have replace the adapters on the ends of the hoses, oiled all the quick-connect connections and refreshed the supplies in the tote so that there will be plenty of hose fittings for the OEX folks. The adapters MAY need an additional tapping once they're onboard if they are leaking a little. I recommend the Leg 1 DL test out the hoses and ask Chip for help with those adapter fittings if they spray weirdly. There are at least 10 firehose fittings, which should last us a while if people don't drop the hose on the deck! Marking this as done  😎
