### ISSUE TITLE
Testing applications

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#135]
In FY24 this task will begin in early March.

All applications used on the vessel during the survey should get a single run through.

Megsie addendum:
* Unless noted otherwise, confirm that all applications are up to date and that you can open them. Where relevant, some on this list will have additional things about the software that you'll need to test.

# All computers (I think)

- [ ] [HP1006 Printer drivers](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/HP1006_drivers)

# Metis computer
## Basics

- [x] MS Office or [File format converter (docx xlsx)](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/docx_xlsx_file_converter) - make sure you can open it.
- [ ] [HP1006 Printer drivers](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/HP1006_drivers) - to check, go to Printers and Devices in Settings. Scroll down to Related Settings and select Print server properties. Select the Drivers tab, and see if your printer is listed. If it is, you’re all set. Sarah and I installed this on the Metis computer for cloning based on the Survey App. Need to plug into printer to complete install?
- [x] R >= 4.3.0 Open R and check version
- [x] Rtools 4.3 Open R and in the console run `pkgbuild::rtools_path()` and check the version. It should say something like `C:\\RBuildTools\\4.3/usr/bin`
- [x] R Studio (latest version) - should be something like 2023.12.1 for AI 2024 survey.
- [x] [GAPsurvey R package](https://github.com/afsc-gap-products/GAPsurvey) (latest version when it's available) - install latest version, run some of the function examples.

## Backup CTD data and data processing

- [ ] SBE Data Processing
- [ ] SeaTerm
- [ ] SeaView
- [ ] SBE Data Processing
- [ ] Seasave
- [ ] Prolific serial driver
- [ ] Adobe Acrobat Reader

# Wheelhouse computer

- [x] [HOBO Lite 3.7.8](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/Bottom%20contact%20sensor)
- [ ] [BVDR Converter](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/BVDR_converter/)
- [x] [Hyperterm](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/Hyperterm) ?? for communicating w serial devices.
- [x] [Light Meters](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/Light%20meters) (also **Marport computer**)
- [x] Working version of Wheelhouse
- [x] Calypso
- [x] ArcMap with the survey area map of trawlable/untrawlable stations 
- [x] MS Office suite (Excel, Word, and Access).
- [ ] "Single file" tools like Station Dropping Tool, Net spreadsheets from Shawn
- [ ] R >= 4.3.0
- [ ] Rtools 4.3
- [x] R Studio (latest version)
- [x] GAPsurvey R package (when it's available)
- [x] Adobe Acrobat Reader
- [ ] IMPORTANT: Test upload of .7z data to SFTP site - notify @autumn-farris-noaa when done.

# CTD laptop

- [ ] R >= 4.3.0
- [ ] Rtools 4.3
- [ ] R Studio (latest version)
- [ ] GAPsurvey R package (latest version when it's available)
- [ ] SBE Data Processing
- [ ] Seaterm
- [ ] Seasave
- [ ] Prolific serial driver

# Marport computer

- [ ] [Light Meters](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/Light%20meters)
- [ ] [SiRFDemo](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/GPSs) (for configuring GPS thru serial port)
- [x] CommandView
- [x] Commander (Paul thinks Marport Server is part of Commander, but check with Gary M to make sure).

# Globe computer

- [x] Globe
- [ ] [SiRFDemo](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/GPSs)
- [x] [Tides and Currents](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/Tides%20and%20Currents) (possibly deprecated?)

**Comment by MargaretSiple-NOAA** [comment]
I'm making a note to us here to check the LW parameters in the length standards between GIDES and with the LW parameters from RACE_DATA when we do our run-through! Just want to check something I saw in #107

**Comment by Ned-Laman-NOAA** [comment]
Autumn's comment today in our Team Meeting has me thinking that we need to extract and send some of our test data across the FTP site. However, I first need to confirm with her that the data will/won't be loaded into RACE_DATA as they would with regular @sea data or that she has a plan for that at least.

**Comment by MargaretSiple-NOAA** [comment]
The Bering Sea group tested and added software to the Metis computer: https://github.com/afsc-gap-products/EBS-Survey-Planning/issues/5. So that one should be good to go. Only change since last year (aside from updates) is removing Portfolio. 

I checked off the things I tested last week while I was doing Wheelhouse/Calypso testing.

**Comment by Ned-Laman-NOAA** [comment]
I'm ready to attempt the SFTP test; Autumn assures that we're on a test instance so no reason to hold off sending files.

Working strictly from the Wheelhouse list, here's what I can say:
ArcMap isn't running on the Wheelhouse machine by design. It runs on the Marport machine and currently isn't running on the shop Marport machine with error "host not set" which means (I think) that the seat license is not on that machine.

R version is 3.6.0
RStudio version is 1.1.... (2019)
RTools are not installed

Were things like SunriseSunset and other R-packages and functions written for the survey tested as part of GAPsurvey package?

**Comment by Ned-Laman-NOAA** [comment]
files uploaded to SFTP. waiting to hear how that goes

**Comment by MargaretSiple-NOAA** [comment]
> R version is 3.6.0 RStudio version is 1.1.... (2019) RTools are not installed
> 
> Were things like SunriseSunset and other R-packages and functions written for the survey tested as part of GAPsurvey package?

Yes, the `sunrise_sunset()` functions and all those "loose" functions are now part of the GAPsurvey package, which I know is installed and running on the Wheelhouse machine. W/r/t rtools and the R versions, I have to assume those are ok since Sean tested GAPsurvey on that machine already but we might want to confirm that it's ok.

**Comment by Ned-Laman-NOAA** [comment]
ArcMap testing should not be on the Wheelhouse computer test list since it's always installed on the Marport computer

Nate will follow up about R versions with Sean Rohan since he successfully tested GAPsurvey package with those older versions
