### ISSUE TITLE
Lat-Longs to ArcGIS

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#2]
Send the lat/lon station locations to Bethany and Mark

**Comment by zoyafuso-NOAA** [comment]
Hi all,

The 520 GOA station allocation for 2023 lives in G:\GOA\GOA 2023\Station Allocation\GOA2023_Station_allocation_520_EW.csv. The summary of which strata get bonus stations lives in G:\GOA\GOA 2023\Station Allocation\Extra files\GOA2023_bonus_station_summary.xlsx. 

Let me know if there are other things associated with this task. Otherwise, I can close it out and we can all have one less task to do!

Zack

**Comment by zoyafuso-NOAA** [comment]
I did not get more instructions on this, so I am assuming this task is done and I can close the issue.
