### ISSUE TITLE
Addition of all software on METIS computer, ready for cloning

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#81]
**This is for all METIS computers**

- In addition to the list of software on the Survey App, we need to make sure Metis computers have updates to GAPSurvey R package and Metis.

The following needs to be done on the METIS computer from our side:

- connect tablets via bluetooth using BlueSoleil / Bluetooth Explorer
- transfer raw metis data files
- import into metis and edit in GIDES
- export biological data
- backup database

A couple optional things we could do but didn't last year:

- install driver for HP 1006 (needed to plug directly into printer)
- test CTD data transfer process 
- Check for single-file tools like the station dropping tool

**Comment by SarahFriedman-NOAA** [comment]
@zoyafuso-NOAA needs to be assigned to this task

**Comment by SarahFriedman-NOAA** [comment]
The METIS computer is up to date and almost ready for cloning (pending some testing of the METIS program itself and a few tweaks Chris needs to do). We did the following:

- Updated R, R Studio, and R tools
- Updated the RACE Survey App (not final version, but this will be brought up by FPCs)
- Tested to ensure we could bluetooth data from the tablets to the METIS computer
- Deleted old data files & versions of R

We are still waiting on
- An updated GAPSurvey R package (still in development)
- Need to update printer drivers (need a printer to plug directly into computer) 
- CTD team will ensure SeaBird software is functional, no version updates since 2018

A few notes for this task next year: 
- I made a guide [here](https://docs.google.com/document/d/13kszeZMkNZdlN48RaTnZzUCXbxDpNPaVebdZRBVF_Dc/edit#heading=h.ebwfgxcwbwld)
- Unclear how this task overlaps with #83 
- Probably can have a single team of folks work on this (don't need to split task across EBS/GOA, just made it slightly more confusing)
